postgresql: &postgresql
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: 5
  # host: localhost
  # port: 5432
  username: <%= ENV['USER'] %>
  # password:

development:
  <<: *postgresql
  database: league_development<%= ENV['DB_SUFFIX'] %>

production:
  <<: *postgresql
  database: league_production<%= ENV['DB_SUFFIX'] %>

test: &TEST
  <<: *postgresql
  database: league_test<%= ENV['DB_SUFFIX'].to_s + ENV['TEST_ENV_NUMBER'].to_s %>
